### ISSUE TITLE
Seems to not be working since 0.1.0

### ISSUE THREAD

**Issue by tmob03** [veteran29/steam-url-open-extension#12]
No matter what steam page, I click on the extension and it does nothing. The last I used it was ~a week ago so I can't confirm it's due to 0.1.0, but that's what I'd assume.

How to repro: Go to any steam page on chrome and try to use the extension.

OS: Windows 10 Home 21H2 19044.1706
Browser: Google Chrome Version 102.0.5005.115 (Official Build) (64-bit)
Steam API: v020
Steam package versions: 1654574690

**Comment by veteran29** [comment]
Pushed 0.1.1 update to Chrome Web Store, should fix the issue.

**Comment by tmob03** [comment]
Yep, works now thanks!
