### ISSUE TITLE
0.0.6 does not work on Firefox 122.0.1

### ISSUE THREAD

**Issue by fluxxdog** [veteran29/steam-url-open-extension#17]
Tried clicking on a link to https://store.steampowered.com/app/1245620/ELDEN_RING/ (search from Google)

Expected: Open the store page in Steam (program is open in the background)

Actual: Opens a web page in the browser

Default options from installing from [addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/steam-url-opener/)

**Comment by veteran29** [comment]
Works for me on Firefox 123. 

The extension does not automatically open links in Steam, you need to click the button in the URL bar: 
![image](https://github.com/veteran29/steam-url-open-extension/assets/4293906/7342b4fd-4e7c-4978-b7a8-b45e22dd16be)

**Comment by fluxxdog** [comment]
![image](https://github.com/veteran29/steam-url-open-extension/assets/12112509/f6da36f5-e8a3-4edf-8960-6fb55674a439)
No button either. Also Firefox says latest is 122.0.1 so you might be ahead of me on that. Is there anything changed in 123 that would fix this?

**Comment by veteran29** [comment]
The button shows only on steam related pages. Minor version difference should not matter.

**Comment by fluxxdog** [comment]
Oh. Wow. That was not clear at all. I'll just close this then. I thought to purpose of this was to keep you from going to Steam in your browser to begin with.
