### ISSUE TITLE
Extension does not work on Firefox

### ISSUE THREAD

**Issue by veteran29** [veteran29/steam-url-open-extension#6]
Recent Firefox updates have broken the extension, new tab is opened and Firefox asks for permission to open `steam://` uri type but as the popup is non blocking it's immediately closed by the extension giving user no chance to give the permissions to the extension.

**Comment by Matrix89** [comment]
So, I've just tried fixing it, but it works when I build from source, so I guess updating dependencies fixes the issue

**Comment by MhmdAMiNE** [comment]
> 
> 
> Recent Firefox updates have broken the extension, new tab is opened and Firefox asks for permission to open `steam://` uri type but as the popup is non blocking it's immediately closed by the extension giving user no chance to give the permissions to the extension.

Same thing for me
it's not working :(

**Comment by veteran29** [comment]
Fixed by 0f527e96d2f126237c2f39440113f2338377a6df in release 0.0.4
