### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by BobMaster1982** [veteran29/steam-url-open-extension#7]
No matter on which site I click a link to steam, it does not open in the Steam app.
Even links on the actual Steam website open in my browser.
All I want is to open the links I get from Steam in my mailbox(or any other) directly in the app, is this not possible ?

**Comment by veteran29** [comment]
Please provide more details, what browser, what version, what OS.

You need to open the Steam URL in your browser then click the extension icon to open that URL in the Steam client.

**Comment by BobMaster1982** [comment]
Google Chrome Version 90.0.4430.93 (Official Build) (64-bit)
Windows 10 Version 2004
Opening the link first and then pressing the extension button works, but it's not what I am looking for.
Clicking the link should instantly take me to Steam client.
